name: Hello World

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: npm run build
      - uses: actions/upload-artifact@v7
        with:
          name: application
          path: dist/

  test:
    needs: build
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        node: [ 20, 22 ]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:

    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node }}

    - uses: actions/download-artifact@v7
      with:
        name: application
        path: dist/

    - run: npm run test

    - name: status
      if: always()
      run: echo "Status ${{ job.status }}"
